site_name: Strato Documentation
nav:
  - Home: index.md

  - About: about.md

theme:
  name: material
  #custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
    - toc.integrate
    - navigation.indexes
    - navigation.sections

  logo: assets/logo_round.png
  favicon: assets/favicon.ico

  font:
    text: barlow
 
  language: en

extra_css:
  - stylesheets/extra.css

#repo_url: https://github.com/aau-claaudia

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.keys

  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#  - pymdownx.keys
#  - pymdownx.highlight:
#      linenums: true
#      linenums_style: pymdownx-inline

#  - pymdownx.superfences
#  - pymdownx.snippets

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/claaudia_aau
      name: Claaudia on Twitter

    - icon: fontawesome/solid/paper-plane
      link: mailto:<claaudia@aau.dk>

    - icon: fontawesome/solid/globe
      link: https://www.claaudia.aau.dk/

  #generator: True

copyright: Copyright &copy; 2021 - 2022 Claaudia


#extra_javascript:
#  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
#  - javascripts/config.js
#extra_css:
#  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
